export * from './dashboard/Dashboard'
export * from './pessoas/DetalheDePessoas'
export * from './pessoas/ListagemDePessoas'
export * from './instagram/ListagemDeInstagram'
export * from './sobre/Sobre'
